# Generated by Django 3.2 on 2021-04-08 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_community_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ('name',), 'permissions': [('community_owner', 'Community owner'), ('community_member', 'Community member')], 'verbose_name': 'community', 'verbose_name_plural': 'communities'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('username',), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
