# Generated by Django 3.2 on 2021-07-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210408_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='communities', verbose_name='photo'),
        ),
    ]
